### ISSUE TITLE
More Searxng warnings

### ISSUE THREAD

**Issue by arsaboo** [yokingma/search_with_ai#13]
Here are other errors that I am seeing in the searxng container. I am guessing they can be ignored, but wanted to check with you. 
```bash
2024-05-11 21:51:36,045 WARNING:searx.engines.internetarchivescholar: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.HTTPStatusError', None, ('400', 'Bad Request', 'scholar.archive.org')) False
2024-05-11 21:51:36,045 ERROR:searx.engines.internetarchivescholar: requests exception (search duration : 1.4337322499995935 s, timeout: 15.0 s) : Client error '400 Bad Request' for url 'https://scholar.archive.org/search?q=what+are+the+effects+of+newspaper+closures&limit=15&offset=0'
For more information check: https://httpstatuses.com/400
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 147, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 116, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 289, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 285, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 245, in patch_response
    raise_for_httperror(response)
  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 77, in raise_for_httperror
    resp.raise_for_status()
  File "/usr/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://scholar.archive.org/search?q=what+are+the+effects+of+newspaper+closures&limit=15&offset=0'
For more information check: https://httpstatuses.com/400
2024-05-11 21:57:27,024 WARNING:searx.engines.internetarchivescholar: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'httpx.HTTPStatusError', None, ('400', 'Bad Request', 'scholar.archive.org')) False
2024-05-11 21:57:27,024 ERROR:searx.engines.internetarchivescholar: requests exception (search duration : 0.3081536669997149 s, timeout: 15.0 s) : Client error '400 Bad Request' for url 'https://scholar.archive.org/search?q=what+are+the+effects+of+newspaper+closures&limit=15&offset=0'
For more information check: https://httpstatuses.com/400
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 147, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 116, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 289, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 285, in call_client
    raise e
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 245, in patch_response
    raise_for_httperror(response)
  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 77, in raise_for_httperror
    resp.raise_for_status()
  File "/usr/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://scholar.archive.org/search?q=what+are+the+effects+of+newspaper+closures&limit=15&offset=0'
For more information check: https://httpstatuses.com/400
```

**Comment by yokingma** [comment]
The Docker image used by SearXNG is the official image. If it works properly, may be you can ignore them :).

**Comment by arsaboo** [comment]
See a simple docker compose - https://github.com/ItzCrazyKns/Perplexica/blob/master/docker-compose.yaml
