### ISSUE TITLE
我用mac运行和arm的服务器都起来了，但是都遇到了模型无法选择，searx搜索也一直报超时的错误问题

### ISSUE THREAD

**Issue by brookxs** [yokingma/search_with_ai#89]
![QQ_1732121743574](https://github.com/user-attachments/assets/c57ee830-2718-4ece-9283-27e57b4c85ce)
模型配置了openai和deepseek都获取不到，我用的mac的和arm的服务器都不得，两个都是arm架构的。还有就是searx一直报错
```2024-11-20 16:48:49,705 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
2024-11-21 00:48:49 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffa422c0b0 pid: 21 (default app)
2024-11-21 00:48:49 2024-11-20 16:48:49,708 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
2024-11-21 00:48:49 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffa422c0b0 pid: 23 (default app)
2024-11-21 00:48:49 2024-11-20 16:48:49,772 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
2024-11-21 00:48:49 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffa422c0b0 pid: 28 (default app)
2024-11-21 00:48:52 2024-11-20 16:48:52,820 ERROR:searx.engines.wikidata: Fail to initialize
2024-11-21 00:48:52 Traceback (most recent call last):
2024-11-21 00:48:52   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
2024-11-21 00:48:52     return future.result(timeout)
2024-11-21 00:48:52            ^^^^^^^^^^^^^^^^^^^^^^
2024-11-21 00:48:52   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result
2024-11-21 00:48:52     raise TimeoutError()
2024-11-21 00:48:52 TimeoutError
2024-11-21 00:48:52 
2024-11-21 00:48:52 The above exception was the direct cause of the following exception:
2024-11-21 00:48:52 
2024-11-21 00:48:52 Traceback (most recent call last):
2024-11-21 00:48:52   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
2024-11-21 00:48:52     self.engine.init(get_engine_from_settings(self.engine_name))
2024-11-21 00:48:52   File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
2024-11-21 00:48:52     jsonresponse = send_wikidata_query(query)
2024-11-21 00:48:52                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21 00:48:52   File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
2024-11-21 00:48:52     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
2024-11-21 00:48:52                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21 00:48:52   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
2024-11-21 00:48:52     return request('get', url, **kwargs)
2024-11-21 00:48:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21 00:48:52   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
2024-11-21 00:48:52     raise httpx.TimeoutException('Timeout', request=None) from e
2024-11-21 00:48:52 httpx.TimeoutException: Timeout
2024-11-21 00:48:52 2024-11-20 16:48:52,847 ERROR:searx.engines.soundcloud: Fail to initialize
2024-11-21 00:48:52 Traceback (most recent call last):
2024-11-21 00:48:52   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
2024-11-21 00:48:52     return future.result(timeout)
2024-11-21 00:48:52            ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by brookxs** [comment]
解决了，原来是构建的时候没有把我的配置信息放到配置文件里面去

**Comment by yaleimeng** [comment]
@brookxs  你好，我遇到跟你一样的问题，也是大模型下拉框没有内容，无法选择。具体怎么操作才能解决呢？

**Comment by yokingma** [comment]
@yaleimeng 在使用docker compose启动服务的时候，需要注意两个配置文件: [model.json](https://github.com/yokingma/search_with_ai/blob/main/deploy/model.json), [.env.docker](https://github.com/yokingma/search_with_ai/blob/main/deploy/.env.docker) 在 [docker-compose.yaml](https://github.com/yokingma/search_with_ai/blob/main/deploy/docker-compose.yaml) 同级别目录下。

这两个文件里配置模型服务的基本信息（比如baseURL，KEY）

**Comment by yaleimeng** [comment]
使用docker部署了，app/server目录下的.env 和 Deploy目录下  model.json, .env.docker 配置改了很多遍。 搞不清楚改哪个有用？ 设置了KEY之后，好像某些大模型接口能选择了，但Ollma接口跟我本地配置的不一致。
![Image](https://github.com/user-attachments/assets/15947a10-f939-4dd9-bd30-f1a9fa975d0e)  

![Image](https://github.com/user-attachments/assets/d58abc14-532f-4115-8b55-2a8b3a8e1079)
其中  "baseURL"，我使用  "http://host.docker.internal  和 127.0.0.1 都不行。。真是醉了。

**Comment by yaleimeng** [comment]
我现在明白了。 docker-compose.yaml 中配置的信息，其中volume
image: docker.cnb.cool/aigc/aisearch
    volumes:
      - ./.env.docker:/app/.env
      - ./model.json:/app/dist/model.json
  只需要修改deploy目录下的这两个文件就行。  : 之后的文件路径是docker镜像运行的内部路径，不能改。

**Comment by yokingma** [comment]
> 我现在明白了。 docker-compose.yaml 中配置的信息，其中volume image: docker.cnb.cool/aigc/aisearch volumes: - ./.env.docker:/app/.env - ./model.json:/app/dist/model.json 只需要修改deploy目录下的这两个文件就行。 : 之后的文件路径是docker镜像运行的内部路径，不能改。

对的.

**Comment by yaleimeng** [comment]
不过docker镜像好像没有及时更新。Tavily搜索还是不能用。只能再去费劲折腾源码运行。

**Comment by yokingma** [comment]
@yaleimeng 用的是 `docker pull docker.cnb.cool/aigc/aisearch` 这个镜像吗？这几天会更新新的能力：DeepResearch

**Comment by yaleimeng** [comment]
是的，按readme中指引提到的镜像。
